name: pyg4ometry

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
  release:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:

  build-and-test:
    name: Test pyg4ometry with Python
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        os: [ubuntu-latest, macOS-latest]
    steps:
    - name: Install non-pip dependencies on Ubuntu
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install libboost-dev libcgal-dev libgmp-dev libmpfr-dev libocct-* libtbb-dev libxi-dev libvtk9-dev occt-misc
    - name: Install non-pip dependencies on MacOS
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install boost cgal gmp mpfr opencascade tbb vtk
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Get dependencies and install pyg4ometry
      run: |
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install --upgrade .[test]
    - name: Run unit tests
      run: |
        pytest
        
  test-in-container:
    name: Test in Docker container
    runs-on: ubuntu-latest
    container: docker://gipert/pyg4ometry:latest
    steps:
    - uses: actions/checkout@v2
    - name: Get dependencies and install pyg4ometry
      run: |
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install --upgrade .[test]
    - name: Run unit tests
      run: |
        pytest

  test-coverage:
    name: Calculate and upload test coverage
    runs-on: ubuntu-latest
    steps:
    - name: Install non-pip dependencies on Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install libboost-dev libcgal-dev libgmp-dev libmpfr-dev libocct-* libtbb-dev libxi-dev libvtk9-dev occt-misc
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Generate Report
      run: |
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install --upgrade .[test]
        pytest --cov=pyg4ometry --cov-report=xml
    - name: Upload Coverage to codecov.io
      uses: codecov/codecov-action@v3
